package:
  name: pyinventrry 
  version: "0.1"

source:
  path: ../. 

build:
  entry_points:
    - scoreCalcule=pyinventrry.scoreCalcule:main
requirements:
  run:
    - python >=3
    - numpy
    - pandas >=0.20

test:

about:
  home:
  license:
  license_file:
