package:
  name: pyinventrry 
  version: "0.1"

source:
  path: . 

build:
  entry_point:
    scoreCalcule = scoreCalcule

requirements:
  run:
    - python
    - numpy
    - pandas >=0.20

test:

about:
  home:
  license:
  license_file:
