package:
	name: pyinventrry 
	version: "0.1"

source:
	git_rev: 
	git_url: https://github.com/ewan/inventrry

requirements:
	host:
		- python
		- setuptools


	run:
		- python
		- numpy
		- pandas >= 0.20

test:
	imports:
		- pyinventrry

about:
	home:
	license:
	license_file: